import { createContext, useContext, useState, useMemo, ReactNode } from 'react';

export type Language = 'en' | 'hi' | 'te';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

// Translation data
const translations = {
  en: {
    // Header
    'header.cropPredict': 'CropPredict',
    'header.home': 'Home',
    'header.features': 'Features',
    'header.about': 'About',
    'header.signIn': 'Sign In',
    'header.signUp': 'Sign Up',
    'header.welcome': 'Welcome',
    'header.logout': 'Logout',
    'header.language': 'Language',
    
    // Hero
    'hero.title': 'Smart Crop Prediction for Better Harvests',
    'hero.subtitle': 'Use AI-powered analysis to predict crop yields, optimize farming strategies, and maximize your agricultural productivity.',
    'hero.predictButton': 'Start Predicting',
    'hero.weatherButton': 'Weather Forecast',
    'hero.smartAgriculture': 'Smart Agriculture Solutions',
    'hero.aiPowered': 'Smart AI-Powered',
    'hero.cropSolutions': 'Crop Solutions',
    'hero.description': 'Get instant crop predictions and disease detection with our advanced AI technology. Make data-driven farming decisions that increase your yield and reduce risks.',
    'hero.predictNow': 'Predict Now',
    'hero.detectDisease': 'Detect Disease',
    'hero.accuracyRate': 'Accuracy Rate',
    'hero.farmersTrust': 'Farmers Trust Us',
    'hero.cropTypes': 'Crop Types',
    'hero.predictionReady': 'Prediction Ready',
    'hero.cornYield': 'Corn yield: 85% probability',
    'hero.yieldIncrease': 'Yield Increase',
    
    // Features
    'features.prediction.title': 'Crop Yield Prediction',
    'features.prediction.desc': 'Get accurate yield forecasts using advanced ML algorithms',
    'features.weather.title': 'Weather Integration',
    'features.weather.desc': 'Real-time weather data to optimize your farming decisions',
    'features.soil.title': 'Soil Analysis',
    'features.soil.desc': 'Comprehensive soil health assessment and recommendations',
    'features.market.title': 'Market Trends',
    'features.market.desc': 'Real-time crop prices, market insights, and production recommendations for Andhra Pradesh',
    'features.chat.title': 'AI Assistant',
    'features.chat.desc': 'Get instant answers to your farming questions',
    'features.voice.title': 'Voice Assistant',
    'features.voice.desc': 'Speak naturally to get farming advice, crop recommendations, and agricultural insights',
    'features.coreTitle': 'AI-Powered Core Features',
    'features.coreSubtitle': 'Our most advanced AI capabilities for instant crop insights and disease detection.',
    'features.cropPrediction': 'Crop Prediction',
    'features.cropPredictionDesc': 'Get instant AI-powered crop recommendations based on soil conditions, weather patterns, and optimal farming practices.',
    'features.diseaseDetection': 'Disease Detection',
    'features.diseaseDetectionDesc': 'Upload plant photos or use your camera to instantly detect diseases and receive expert treatment recommendations.',
    'features.additionalTitle': 'Additional Tools & Analytics',
    'features.additionalSubtitle': 'Comprehensive farming tools to enhance your agricultural operations and decision-making.',
    'features.accessFeature': 'Access Feature',
    'features.transformTitle': 'Transform Your Farming Today',
    'features.transformSubtitle': 'Join thousands of farmers using AI to increase yields, reduce risks, and make smarter farming decisions.',
    'features.getStarted': 'Get Started Free',
    'features.watchDemo': 'Watch Demo',
    
    // Auth
    'auth.signin.title': 'Welcome Back',
    'auth.signin.subtitle': 'Sign in to access your crop prediction dashboard',
    'auth.signup.title': 'Join CropPredict',
    'auth.signup.subtitle': 'Create your account to start predicting',
    'auth.name': 'Full Name',
    'auth.phone': 'Phone Number',
    'auth.email': 'Email Address',
    'auth.password': 'Password',
    'auth.confirmPassword': 'Confirm Password',
    'auth.signin': 'Sign In',
    'auth.signup': 'Sign Up',
    'auth.forgotPassword': 'Forgot Password?',
    'auth.noAccount': 'Don\'t have an account?',
    'auth.hasAccount': 'Already have an account?',
    'auth.verifyPhone': 'Verify Phone Number',
    'auth.enterCode': 'Enter the 6-digit code sent to your phone',
    'auth.verify': 'Verify',
    'auth.resendCode': 'Resend Code',
    'auth.changeNumber': 'Change Number',
    
    // Profile
    'profile.title': 'Your Profile',
    'profile.subtitle': 'Manage your account settings and preferences',
    'profile.personalInfo': 'Personal Information',
    'profile.farmInfo': 'Farm Information',
    'profile.preferences': 'Preferences',
    'profile.farmLocation': 'Farm Location',
    'profile.farmSize': 'Farm Size (acres)',
    'profile.primaryCrops': 'Primary Crops',
    'profile.farmingExperience': 'Years of Farming Experience',
    'profile.notifications': 'Notifications',
    'profile.emailNotifications': 'Email Notifications',
    'profile.smsNotifications': 'SMS Notifications',
    'profile.weatherAlerts': 'Weather Alerts',
    'profile.marketUpdates': 'Market Updates',
    'profile.save': 'Save Changes',
    'profile.saved': 'Profile updated successfully!',
    
    // Crop Prediction
    'predict.title': 'Crop Yield Prediction',
    'predict.subtitle': 'Get AI-powered predictions for your crops',
    'predict.manualInput': 'Manual Input',
    'predict.aiPrediction': 'AI Prediction',
    'predict.cropType': 'Crop Type',
    'predict.soilType': 'Soil Type',
    'predict.nitrogen': 'Nitrogen (N)',
    'predict.phosphorus': 'Phosphorus (P)',
    'predict.potassium': 'Potassium (K)',
    'predict.temperature': 'Temperature (°C)',
    'predict.humidity': 'Humidity (%)',
    'predict.rainfall': 'Rainfall (mm)',
    'predict.ph': 'pH Level',
    'predict.predict': 'Predict Yield',
    'predict.results': 'Prediction Results',
    'predict.expectedYield': 'Expected Yield',
    'predict.confidence': 'Confidence Level',
    'predict.recommendations': 'Recommendations',
    'predict.newPrediction': 'New Prediction',
    
    // Weather
    'weather.title': 'Weather Forecast',
    'weather.subtitle': 'Real-time weather data for informed farming decisions',
    'weather.current': 'Current Weather',
    'weather.forecast': '7-Day Forecast',
    'weather.temperature': 'Temperature',
    'weather.humidity': 'Humidity',
    'weather.windSpeed': 'Wind Speed',
    'weather.pressure': 'Pressure',
    'weather.visibility': 'Visibility',
    'weather.uvIndex': 'UV Index',
    'weather.rainfall': 'Rainfall',
    'weather.cloudCover': 'Cloud Cover',
    'weather.today': 'Today',
    'weather.tomorrow': 'Tomorrow',
    'weather.weatherWarnings': 'Weather Warnings',
    'weather.noWarnings': 'No active weather warnings',
    
    // Market Trends
    'market.title': 'Market Trends',
    'market.subtitle': 'Real-time crop prices and market insights',
    'market.prices': 'Current Prices',
    'market.trends': 'Price Trends',
    'market.forecasting': 'Price Forecasting',
    'market.crop': 'Crop',
    'market.currentPrice': 'Current Price',
    'market.change': 'Change',
    'market.volume': 'Volume',
    'market.high': 'High',
    'market.low': 'Low',
    'market.last7Days': 'Last 7 Days',
    'market.last30Days': 'Last 30 Days',
    'market.last3Months': 'Last 3 Months',
    'market.location': 'Location',
    'market.selectLocation': 'Select your location for localized market data',
    'market.andhrapradesh': 'Andhra Pradesh',
    'market.telangana': 'Telangana',
    'market.karnataka': 'Karnataka',
    'market.tamilnadu': 'Tamil Nadu',
    'market.forecastingDesc': 'Predicted price trends for the next 3 months',
    'market.increaseExpected': 'Increase expected',
    'market.decreaseExpected': 'Decrease expected',
    'market.stablePrices': 'Stable prices',
    'market.nextQuarter': 'Next Quarter',
    'market.locationPermission': 'Location Permission Required',
    'market.locationNotice': 'To provide accurate market data specific to your region, please allow location access or manually enter your location.',
    'market.enterLocation': 'Enter your location...',
    'market.useCurrentLocation': 'Use Current Location',
    
    // Soil Analysis
    'soil.title': 'Soil Analysis',
    'soil.subtitle': 'Comprehensive soil health assessment and recommendations',
    
    // Disease Detection
    'disease.title': 'Disease Detection',
    'disease.subtitle': 'AI-powered plant disease identification and treatment recommendations',
    'disease.uploadImage': 'Upload Plant Image',
    'disease.dragDrop': 'Drag and drop an image here, or click to select',
    'disease.analyzing': 'Analyzing image...',
    'disease.results': 'Detection Results',
    'disease.confidence': 'Confidence',
    'disease.symptoms': 'Symptoms',
    'disease.treatment': 'Treatment',
    'disease.prevention': 'Prevention',
    'disease.newAnalysis': 'Analyze Another Image',
    'disease.healthy': 'Plant appears healthy',
    'disease.detected': 'Disease detected',
    'disease.uploadAnother': 'Upload Another Image',
    
    // Voice Assistant
    'voice.title': 'Voice Assistant',
    'voice.subtitle': 'Talk to our AI assistant about farming questions',
    'voice.listening': 'Listening...',
    'voice.processing': 'Processing...',
    'voice.speaking': 'Speaking...',
    'voice.startVoiceChat': 'Start Voice Chat',
    'voice.stopListening': 'Stop Listening',
    'voice.conversation': 'Conversation',
    'voice.placeholder': 'Type your farming question here...',
    'voice.clearChat': 'Clear Chat',
    'voice.audioEnabled': 'Audio Enabled',
    'voice.audioDisabled': 'Audio Disabled',
    'voice.greeting': "Hello! I'm your AI farming assistant. You can ask me about crop diseases, weather patterns, soil management, pest control, or any other agricultural topics. You can speak to me or type your questions.",
    
    // Chatbot
    'chat.title': 'AI Assistant',
    'chat.subtitle': 'Ask me anything about farming, crops, or agriculture',
    'chat.placeholder': 'Type your question here...',
    'chat.send': 'Send',
    'chat.greeting': "Hello! I'm your agricultural AI assistant. How can I help you today?",
    'chat.aiAssistant': 'AI Assistant',
    'chat.farmingAssistant': 'Use the floating chat button to start a conversation with our AI farming assistant.',
    'chat.backToHome': 'Back to Home',
    
    // Footer
    'footer.aboutUs': 'About Us',
    'footer.services': 'Services',
    'footer.support': 'Support',
    'footer.contact': 'Contact',
    'footer.cropPrediction': 'Crop Prediction',
    'footer.weatherData': 'Weather Data',
    'footer.soilAnalysis': 'Soil Analysis',
    'footer.marketInsights': 'Market Insights',
    'footer.helpCenter': 'Help Center',
    'footer.documentation': 'Documentation',
    'footer.faq': 'FAQ',
    'footer.customerSupport': 'Customer Support',
    'footer.rights': 'All rights reserved',
    'footer.termsOfService': 'Terms of Service',
    'footer.privacyPolicy': 'Privacy Policy',
    
    // Common
    'common.back': 'Back',
    'common.next': 'Next',
    'common.loading': 'Loading...',
    'common.error': 'Error',
    'common.success': 'Success',
    'common.cancel': 'Cancel'
  },
  
  hi: {
    // Header
    'header.cropPredict': 'क्रॉपप्रेडिक्ट',
    'header.home': 'होम',
    'header.features': 'विशेषताएं',
    'header.about': 'हमारे बारे में',
    'header.signIn': 'साइन इन',
    'header.signUp': 'साइन अप',
    'header.welcome': 'स्वागत',
    'header.logout': 'लॉग आउट',
    'header.language': 'भाषा',
    
    // Hero
    'hero.title': 'बेहतर फसल के लिए स्मार्ट फसल भविष्यवाणी',
    'hero.subtitle': 'फसल की पैदावार की भविष्यवाणी करने, खेती की रणनीतियों को अनुकूलित करने और अपनी कृषि उत्पादकता को अधिकतम करने के लिए AI-संचालित विश्लेषण का उपयोग करें।',
    'hero.predictButton': 'भविष्यवाणी शुरू करें',
    'hero.weatherButton': 'मौसम पूर्वानुमान',
    'hero.smartAgriculture': 'स्मार्ट कृषि समाधान',
    'hero.aiPowered': 'स्मार्ट AI-संचालित',
    'hero.cropSolutions': 'फसल समाधान',
    'hero.description': 'हमारी उन्नत AI तकनीक के साथ तुरंत फसल भविष्यवाणी और रोग पहचान प्राप्त करें। डेटा-संचालित खेती निर्णय लें जो आपकी पैदावार बढ़ाएं और जोखिम कम करें।',
    'hero.predictNow': 'अभी भविष्यवाणी करें',
    'hero.detectDisease': 'रोग का पता लगाएं',
    'hero.accuracyRate': 'सटीकता दर',
    'hero.farmersTrust': 'किसान हम पर भरोसा करते हैं',
    'hero.cropTypes': 'फसल प्रकार',
    'hero.predictionReady': 'भविष्यवाणी तैयार',
    'hero.cornYield': 'मक्का उत्पादन: 85% संभावना',
    'hero.yieldIncrease': 'उत्पादन वृद्धि',
    
    // Features
    'features.prediction.title': 'फसल उत्पादन भविष्यवाणी',
    'features.prediction.desc': 'उन्नत ML एल्गोरिदम का उपयोग करके सटीक उत्पादन पूर्वानुमान प्राप्त करें',
    'features.weather.title': 'मौसम एकीकरण',
    'features.weather.desc': 'आपके खेती के निर्णयों को अनुकूलित करने के लिए वास्तविक समय मौसम डेटा',
    'features.soil.title': 'मिट्टी विश्लेषण',
    'features.soil.desc': 'व्यापक मिट्टी स्वास्थ्य मूल्यांकन और सिफारिशें',
    'features.market.title': 'बाजार रुझान',
    'features.market.desc': 'आंध्र प्रदेश के लिए वास्तविक समय फसल कीमतें, बाजार अंतर्दृष्टि और उत्पादन सिफारिशें',
    'features.chat.title': 'AI असिस्टेंट',
    'features.chat.desc': 'अपने खेती के सवालों के तुरंत जवाब पाएं',
    'features.voice.title': 'वॉयस असिस्टेंट',
    'features.voice.desc': 'खेती की सलाह, फसल की सिफारिशें और कृषि अंतर्दृष्टि पाने के लिए स्वाभाविक रूप से बोलें',
    'features.coreTitle': 'AI-संचालित मुख्य सुविधाएं',
    'features.coreSubtitle': 'तुरंत फसल अंतर्दृष्टि और रोग पहचान के लिए हमारी सबसे उन्नत AI क्षमताएं।',
    'features.cropPrediction': 'फसल भविष्यवाणी',
    'features.cropPredictionDesc': 'मिट्टी की स्थिति, मौसम पैटर्न और इष्टतम कृषि प्रथाओं के आधार पर तुरंत AI-संचालित फसल सिफारिशें प्राप्त करें।',
    'features.diseaseDetection': 'रोग पहचान',
    'features.diseaseDetectionDesc': 'पौधों की तस्वीरें अपलोड करें या तुरंत रोगों का पता लगाने और विशेषज्ञ उपचार सिफारिशें प्राप्त करने के लिए अपना कैमरा उपयोग करें।',
    'features.additionalTitle': 'अतिरिक्त उपकरण और विश्लेषण',
    'features.additionalSubtitle': 'आपके कृषि संचालन और निर्णय लेने को बढ़ाने के लिए व्यापक कृषि उपकरण।',
    'features.accessFeature': 'फीचर एक्सेस करें',
    'features.transformTitle': 'आज ही अपनी खेती को बदलें',
    'features.transformSubtitle': 'हजारों किसानों के साथ जुड़ें जो उत्पादन बढ़ाने, जोखिम कम करने और स्मार्ट खेती के निर्णय लेने के लिए AI का उपयोग कर रहे हैं।',
    'features.getStarted': 'मुफ्त में शुरू करें',
    'features.watchDemo': 'डेमो देखें',
    
    // Auth
    'auth.signin.title': 'वापस स्वागत है',
    'auth.signin.subtitle': 'अपने फसल भविष्यवाणी डैशबोर्ड तक पहुंचने के लिए साइन इन करें',
    'auth.signup.title': 'क्रॉपप्रेडिक्ट में शामिल हों',
    'auth.signup.subtitle': 'भविष्यवाणी शुरू करने के लिए अपना खाता बनाएं',
    'auth.name': 'पूरा नाम',
    'auth.phone': 'फोन नंबर',
    'auth.email': 'ईमेल पता',
    'auth.password': 'पासवर्ड',
    'auth.confirmPassword': 'पासवर्ड की पुष्टि करें',
    'auth.signin': 'साइन इन',
    'auth.signup': 'साइन अप',
    'auth.forgotPassword': 'पासवर्ड भूल गए?',
    'auth.noAccount': 'कोई खाता नहीं है?',
    'auth.hasAccount': 'पहले से ही एक खाता है?',
    'auth.verifyPhone': 'फोन नंबर सत्यापित करें',
    'auth.enterCode': 'अपने फोन पर भेजे गए 6-अंकीय कोड को दर्ज करें',
    'auth.verify': 'सत्यापित करें',
    'auth.resendCode': 'कोड फिर से भेजें',
    'auth.changeNumber': 'नंबर बदलें',
    
    // Profile
    'profile.title': 'आपकी प्रोफ़ाइल',
    'profile.subtitle': 'अपनी खाता सेटिंग्स और प्राथमिकताओं का प्रबंधन करें',
    'profile.personalInfo': 'व्यक्तिगत जानकारी',
    'profile.farmInfo': 'खेत की जानकारी',
    'profile.preferences': 'प्राथमिकताएं',
    'profile.farmLocation': 'खेत का स्थान',
    'profile.farmSize': 'खेत का आकार (एकड़)',
    'profile.primaryCrops': 'मुख्य फसलें',
    'profile.farmingExperience': 'खेती का अनुभव (वर्ष)',
    'profile.notifications': 'सूचनाएं',
    'profile.emailNotifications': 'ईमेल सूचनाएं',
    'profile.smsNotifications': 'SMS सूचनाएं',
    'profile.weatherAlerts': 'मौसम अलर्ट',
    'profile.marketUpdates': 'बाजार अपडेट',
    'profile.save': 'परिवर्तन सहेजें',
    'profile.saved': 'प्रोफ़ाइल सफलतापूर्वक अपडेट की गई!',
    
    // Crop Prediction
    'predict.title': 'फसल उत्पादन भविष्यवाणी',
    'predict.subtitle': 'अपनी फसलों के लिए AI-संचालित भविष्यवाणियां प्राप्त करें',
    'predict.manualInput': 'मैनुअल इनपुट',
    'predict.aiPrediction': 'AI भविष्यवाणी',
    'predict.cropType': 'फसल का प्रकार',
    'predict.soilType': 'मिट्टी का प्रकार',
    'predict.nitrogen': 'नाइट्रोजन (N)',
    'predict.phosphorus': 'फास्फोरस (P)',
    'predict.potassium': 'पोटेशियम (K)',
    'predict.temperature': 'तापमान (°C)',
    'predict.humidity': 'आर्द्रता (%)',
    'predict.rainfall': 'वर्षा (mm)',
    'predict.ph': 'pH स्तर',
    'predict.predict': 'उत्पादन की भविष्यवाणी करें',
    'predict.results': 'भविष्यवाणी परिणाम',
    'predict.expectedYield': 'अपेक्षित उत्पादन',
    'predict.confidence': 'विश्वसनीयता स्तर',
    'predict.recommendations': 'सिफारिशें',
    'predict.newPrediction': 'नई भविष्यवाणी',
    
    // Weather
    'weather.title': 'मौसम पूर्वानुमान',
    'weather.subtitle': 'सूचित खेती निर्णयों के लिए वास्तविक समय मौसम डेटा',
    'weather.current': 'वर्तमान मौसम',
    'weather.forecast': '7-दिन का पूर्वानुमान',
    'weather.temperature': 'तापमान',
    'weather.humidity': 'आर्द्रता',
    'weather.windSpeed': 'हवा की गति',
    'weather.pressure': 'दबाव',
    'weather.visibility': 'दृश्यता',
    'weather.uvIndex': 'UV सूचकांक',
    'weather.rainfall': 'वर्षा',
    'weather.cloudCover': 'बादल कवर',
    'weather.today': 'आज',
    'weather.tomorrow': 'कल',
    'weather.weatherWarnings': 'मौसम चेतावनी',
    'weather.noWarnings': 'कोई सक्रिय मौसम चेतावनी नहीं',
    
    // Market Trends
    'market.title': 'बाजार रुझान',
    'market.subtitle': 'वास्तविक समय फसल कीमतें और बाजार अंतर्दृष्टि',
    'market.prices': 'वर्तमान कीमतें',
    'market.trends': 'मूल्य रुझान',
    'market.forecasting': 'मूल्य पूर्वानुमान',
    'market.crop': 'फसल',
    'market.currentPrice': 'वर्तमान मूल्य',
    'market.change': 'परिवर्तन',
    'market.volume': 'मात्रा',
    'market.high': 'उच्च',
    'market.low': 'निम्न',
    'market.last7Days': 'पिछले 7 दिन',
    'market.last30Days': 'पिछले 30 दिन',
    'market.last3Months': 'पिछले 3 महीने',
    'market.location': 'स्थान',
    'market.selectLocation': 'स्थानीयकृत बाजार डेटा के लिए अपना स्थान चुनें',
    'market.andhrapradesh': 'आंध्र प्रदेश',
    'market.telangana': 'तेलंगाना',
    'market.karnataka': 'कर्नाटक',
    'market.tamilnadu': 'तमिलनाडु',
    'market.forecastingDesc': 'अगले 3 महीनों के लिए अनुमानित मूल्य रुझान',
    'market.increaseExpected': 'वृद्धि की उम्मीद',
    'market.decreaseExpected': 'कमी की उम्मीद',
    'market.stablePrices': 'स्थिर कीमतें',
    'market.nextQuarter': 'अगली तिमाही',
    'market.locationPermission': 'स्थान अनुमति आवश्यक',
    'market.locationNotice': 'आपके क्षेत्र के लिए विशिष्ट सटीक बाजार डेटा प्रदान करने के लिए, कृपया स्थान पहुंच की अनुमति दें या मैन्यूअल रूप से अपना स्थान दर्ज करें।',
    'market.enterLocation': 'अपना स्थान दर्ज करें...',
    'market.useCurrentLocation': 'वर्तमान स्थान का उपयोग करें',
    
    // Soil Analysis
    'soil.title': 'मिट्टी विश्लेषण',
    'soil.subtitle': 'व्यापक मिट्टी स्वास्थ्य मूल्यांकन और सिफारिशें',
    
    // Disease Detection
    'disease.title': 'रोग पहचान',
    'disease.subtitle': 'AI-संचालित पौधों की बीमारी की पहचान और उपचार सिफारिशें',
    'disease.uploadImage': 'पौधे की छवि अपलोड करें',
    'disease.dragDrop': 'यहाँ एक छवि खींचें और छोड़ें, या चुनने के लिए क्लिक करें',
    'disease.analyzing': 'छवि का विश्लेषण...',
    'disease.results': 'पहचान परिणाम',
    'disease.confidence': 'विश्वसनीयता',
    'disease.symptoms': 'लक्षण',
    'disease.treatment': 'उपचार',
    'disease.prevention': 'रोकथाम',
    'disease.newAnalysis': 'दूसरी छवि का विश्लेषण करें',
    'disease.healthy': 'पौधा स्वस्थ दिखता है',
    'disease.detected': 'बीमारी का पता चला',
    'disease.uploadAnother': 'दूसरी छवि अपलोड करें',
    
    // Voice Assistant
    'voice.title': 'वॉयस असिस्टेंट',
    'voice.subtitle': 'खेती के सवालों के बारे में हमारे AI असिस्टेंट से बात करें',
    'voice.listening': 'सुन रहा है...',
    'voice.processing': 'प्रसंस्करण...',
    'voice.speaking': 'बोल रहा है...',
    'voice.startVoiceChat': 'वॉयस चैट शुरू करें',
    'voice.stopListening': 'सुनना बंद करें',
    'voice.conversation': 'बातचीत',
    'voice.placeholder': 'यहाँ अपना खेती का सवाल टाइप करें...',
    'voice.clearChat': 'चैट साफ़ करें',
    'voice.audioEnabled': 'ऑडियो सक्षम',
    'voice.audioDisabled': 'ऑडियो अक्षम',
    'voice.greeting': 'नमस्ते! मैं आपका AI कृषि सहायक हूं। आप मुझसे फसल की बीमारियों, मौसम के पैटर्न, मिट्टी प्रबंधन, कीट नियंत्रण, या किसी भी अन्य कृषि विषयों के बारे में पूछ सकते हैं। आप मुझसे बात कर सकते हैं या अपने प्रश्न टाइप कर सकते हैं।',
    
    // Chatbot
    'chat.title': 'AI असिस्टेंट',
    'chat.subtitle': 'खेती, फसलों, या कृषि के बारे में मुझसे कुछ भी पूछें',
    'chat.placeholder': 'यहाँ अपना प्रश्न टाइप करें...',
    'chat.send': 'भेजें',
    'chat.greeting': 'नमस्ते! मैं आपका कृषि AI असिस्टेंट हूं। आज मैं आपकी कैसे मदद कर सकता हूं?',
    'chat.aiAssistant': 'AI असिस्टेंट',
    'chat.farmingAssistant': 'हमारे AI कृषि सहायक के साथ बातचीत शुरू करने के लिए फ्लोटिंग चैट बटन का उपयोग करें।',
    'chat.backToHome': 'होम पर वापस',
    
    // Footer
    'footer.aboutUs': 'हमारे बारे में',
    'footer.services': 'सेवाएं',
    'footer.support': 'सहायता',
    'footer.contact': 'संपर्क',
    'footer.cropPrediction': 'फसल भविष्यवाणी',
    'footer.weatherData': 'मौसम डेटा',
    'footer.soilAnalysis': 'मिट्टी विश्लेषण',
    'footer.marketInsights': 'बाजार अंतर्दृष्टि',
    'footer.helpCenter': 'सहायता केंद्र',
    'footer.documentation': 'दस्तावेज़ीकरण',
    'footer.faq': 'अक्सर पूछे जाने वाले प्रश्न',
    'footer.customerSupport': 'ग्राहक सहायता',
    'footer.rights': 'सभी अधिकार सुरक्षित',
    'footer.termsOfService': 'सेवा की शर्तें',
    'footer.privacyPolicy': 'गोपनीयता नीति',
    
    // Common
    'common.back': 'वापस',
    'common.next': 'अगला',
    'common.loading': 'लोड हो रहा है...',
    'common.error': 'त्रुटि',
    'common.success': 'सफलता',
    'common.cancel': 'रद्द करें'
  },
  
  te: {
    // Header
    'header.cropPredict': 'క్రాప్‌ప్రెడిక్ట్',
    'header.home': 'హోమ్',
    'header.features': 'ఫీచర్స్',
    'header.about': 'మా గురించి',
    'header.signIn': 'సైన్ ఇన్',
    'header.signUp': 'సైన్ అప్',
    'header.welcome': 'స్వాగతం',
    'header.logout': 'లాగ్ అవుట్',
    'header.language': 'భాష',
    
    // Hero
    'hero.title': 'మెరుగైన పంటల కోసం స్మార్ట్ పంట అంచనా',
    'hero.subtitle': 'పంట దిగుబడి అంచనా వేయడానికి, వ్యవసాయ వ్యూహాలను అనుకూలపరచడానికి మరియు మీ వ్యవసాయ ఉత్పాదకతను గరిష్టంగా పెంచడానికి AI-ఆధారిత విశ్లేషణను ఉపయోగించండి.',
    'hero.predictButton': 'అంచనా ప్రారంభించండి',
    'hero.weatherButton': 'వాతావరణ అంచనా',
    'hero.smartAgriculture': 'స్మార్ట్ వ్యవసాయ పరిష్కారాలు',
    'hero.aiPowered': 'స్మార్ట్ AI-ఆధారిత',
    'hero.cropSolutions': 'పంట పరిష్కారాలు',
    'hero.description': 'మా అధునాతన AI సాంకేతికతతో తక్షణ పంట అంచనాలు మరియు వ్యాధి గుర్తింపును పొందండి. మీ దిగుబడిని పెంచే మరియు ప్రమాదాలను తగ్గించే డేటా-ఆధారిత వ్యవసాయ నిర్ణయాలు తీసు��ోండి.',
    'hero.predictNow': 'ఇప్పుడే అంచనా వేయండి',
    'hero.detectDisease': 'వ్యాధిని గుర్తించండి',
    'hero.accuracyRate': 'ఖచ్చితత్వ రేటు',
    'hero.farmersTrust': 'రైతులు మాపై నమ్మకం ఉంచారు',
    'hero.cropTypes': 'పంట రకాలు',
    'hero.predictionReady': 'అంచనా సిద్ధం',
    'hero.cornYield': 'మొక్కజొన్న దిగుబడి: 85% సంభావ్యత',
    'hero.yieldIncrease': 'దిగుబడి పెరుగుదల',
    
    // Features
    'features.prediction.title': 'పంట దిగుబడి అంచనా',
    'features.prediction.desc': 'అధునాతన ML అల్గారిథమ్‌లను ఉపయోగించి ఖచ్చితమైన దిగుబడి అంచనాలను పొందండి',
    'features.weather.title': 'వాతావరణ సమీకరణ',
    'features.weather.desc': 'మీ వ్యవసాయ నిర్ణయాలను అనుకూలపరచడానికి నిజ-సమయ వాతావరణ డేటా',
    'features.soil.title': 'మట్టి విశ్లేషణ',
    'features.soil.desc': 'సమగ్ర మట్టి ఆరోగ్య మూల్యాంకనం మరియు సిఫారసులు',
    'features.market.title': 'మార్కెట్ ట్రెండ్స్',
    'features.market.desc': 'ఆంధ్రప్రదేశ్ కోసం నిజ-సమయ పంట ధరలు, మార్కెట్ అంతర్దృష్టులు మరియు ఉత్పాదన సిఫార్సులు',
    'features.chat.title': 'AI అసిస్టెంట్',
    'features.chat.desc': 'మీ వ్యవసాయ ప్రశ్నలకు తక్షణ సమాధానాలు పొందండి',
    'features.voice.title': 'వాయిస్ అసిస్టెంట్',
    'features.voice.desc': 'వ్యవసాయ సలహాలు, పంట సిఫార్సులు మరియు వ్యవసాయ అంతర్దృష్టులు పొందడానికి సహజంగా మాట్లాడండి',
    'features.coreTitle': 'AI-ఆధారిత ప్రధాన లక్షణాలు',
    'features.coreSubtitle': 'తక్షణ పంట అంతర్దృష్టులు మరియు వ్యాధి గుర్తింపు కోసం మా అత్యంత అధునాతన AI సామర్థ్యాలు.',
    'features.cropPrediction': 'పంట అంచనా',
    'features.cropPredictionDesc': 'మట్టి పరిస్థితులు, వాతావరణ నమూనాలు మరియు సరైన వ్యవసాయ పద్ధతుల ఆధారంగా తక్షణ AI-ఆధారిత పంట సిఫార్సులను పొందండి.',
    'features.diseaseDetection': 'వ్యాధి గుర్తింపు',
    'features.diseaseDetectionDesc': 'మొక్కల ఫోటోలను అప్‌లోడ్ చేయండి లేదా వ్యాధులను తక్షణమే గుర్తించడానికి మరియు నిపుణుల చికిత్స సిఫార్సులను పొందడానికి మీ కెమెరాను ఉపయోగించండి.',
    'features.additionalTitle': 'అదనపు సాధనాలు మరియు విశ్లేషణలు',
    'features.additionalSubtitle': 'మీ వ్యవసాయ కార్యకలాపాలు మరియు నిర్ణయాలను మెరుగుపరచడానికి సమగ్ర వ్యవసాయ సాధనాలు.',
    'features.accessFeature': 'ఫీచర్‌ను యాక్సెస్ చేయండి',
    'features.transformTitle': 'ఈ రోజే మీ వ్యవసాయాన్ని మార్చండి',
    'features.transformSubtitle': 'దిగుబడిని పెంచడానికి, ప్రమాదాలను తగ్గించడానికి మరియు స్మార్ట్ వ్యవసాయ నిర్ణయాలు తీసుకోవడానికి AIని ఉపయోగిస్తున్న వేలాది రైతులతో చేరండి.',
    'features.getStarted': 'ఉచితంగా ప్రారంభించండి',
    'features.watchDemo': 'డెమో చూడండి',
    
    // Auth
    'auth.signin.title': 'తిరిగి స్వాగతం',
    'auth.signin.subtitle': 'మీ పంట అంచనా డ్యాష్‌బోర్డ్‌ను యాక్సెస్ చేయడానికి సైన్ ఇన్ చేయండి',
    'auth.signup.title': 'క్రాప్‌ప్రెడిక్ట్‌లో చేరండి',
    'auth.signup.subtitle': 'అంచనా ప్రారంభించడానికి మీ ఖాతాను సృష్టించండి',
    'auth.name': 'పూర్తి పేరు',
    'auth.phone': 'ఫోన్ నంబర్',
    'auth.email': 'ఇమెయిల్ చిరునామా',
    'auth.password': 'పాస్‌వర్డ్',
    'auth.confirmPassword': 'పాస్‌వర్డ్‌ను నిర్ధారించండి',
    'auth.signin': 'సైన్ ఇన్',
    'auth.signup': 'సైన్ అప్',
    'auth.forgotPassword': 'పాస్‌వర్డ్ మర్చిపోయారా?',
    'auth.noAccount': 'ఖాతా లేదా?',
    'auth.hasAccount': 'ఇప్పటికే ఖాతా ఉందా?',
    'auth.verifyPhone': 'ఫోన్ నంబర్‌ను ధృవీకరించండి',
    'auth.enterCode': 'మీ ఫోన్‌కు పంపిన 6-అంకెల కోడ్‌ను నమోదు చేయండి',
    'auth.verify': 'ధృవీకరించండి',
    'auth.resendCode': 'కోడ్‌ను మళ్లీ పంపండి',
    'auth.changeNumber': 'నంబర్‌ను మార్చండి',
    
    // Profile
    'profile.title': 'మీ ప్రొఫైల్',
    'profile.subtitle': 'మీ ఖాతా సెట్టింగ్‌లు మరియు ప్రాధాన్యతలను నిర్వహించండి',
    'profile.personalInfo': 'వ్యక్తిగత సమాచారం',
    'profile.farmInfo': 'వ్యవసాయ సమాచారం',
    'profile.preferences': 'ప్రాధాన్యతలు',
    'profile.farmLocation': 'వ్యవసాయ స్థానం',
    'profile.farmSize': 'వ్యవసాయ పరిమాణం (ఎకరాలు)',
    'profile.primaryCrops': 'ప్రధాన పంటలు',
    'profile.farmingExperience': 'వ్యవసాయ అనుభవం (సంవత్సరాలు)',
    'profile.notifications': 'నోటిఫికేషన్‌లు',
    'profile.emailNotifications': 'ఇమెయిల్ నోటిఫికేషన్‌లు',
    'profile.smsNotifications': 'SMS నోటిఫికేషన్‌లు',
    'profile.weatherAlerts': 'వాతావరణ అలర్ట్‌లు',
    'profile.marketUpdates': 'మార్కెట్ అప్‌డేట్‌లు',
    'profile.save': 'మార్పులను సేవ్ చేయండి',
    'profile.saved': 'ప్రొఫైల్ విజయవంతంగా అప్‌డేట్ చేయబడింది!',
    
    // Crop Prediction
    'predict.title': 'పంట దిగుబడి అంచనా',
    'predict.subtitle': 'మీ పంటల కోసం AI-ఆధారిత అంచనాలను పొందండి',
    'predict.manualInput': 'మాన్యువల్ ఇన్‌పుట్',
    'predict.aiPrediction': 'AI అంచనా',
    'predict.cropType': 'పంట రకం',
    'predict.soilType': 'మట్టి రకం',
    'predict.nitrogen': 'నైట్రోజన్ (N)',
    'predict.phosphorus': 'ఫాస్ఫరస్ (P)',
    'predict.potassium': 'పొటాషియం (K)',
    'predict.temperature': 'ఉష్ణోగ్రత (°C)',
    'predict.humidity': 'తేమ (%)',
    'predict.rainfall': 'వర్షపాతం (mm)',
    'predict.ph': 'pH స్థాయి',
    'predict.predict': 'దిగుబడి అంచనా వేయండి',
    'predict.results': 'అంచనా ఫలితాలు',
    'predict.expectedYield': 'ఆశించిన దిగుబడి',
    'predict.confidence': 'విశ్వసనీయత స్థాయి',
    'predict.recommendations': 'సిఫార్సులు',
    'predict.newPrediction': 'కొత్త అంచనా',
    
    // Weather
    'weather.title': 'వాతావరణ అంచనా',
    'weather.subtitle': 'సమాచార వ్యవసాయ నిర్ణయాల కోసం నిజ-సమయ వాతావరణ డేటా',
    'weather.current': 'ప్రస్తుత వాతావరణం',
    'weather.forecast': '7-రోజుల అంచనా',
    'weather.temperature': 'ఉష్ణోగ్రత',
    'weather.humidity': 'తేమ',
    'weather.windSpeed': 'గాలి వేగం',
    'weather.pressure': 'పీడనం',
    'weather.visibility': 'కనిపించే దూరం',
    'weather.uvIndex': 'UV సూచిక',
    'weather.rainfall': 'వర్షపాతం',
    'weather.cloudCover': 'మేఘ కవర్',
    'weather.today': 'ఈరోజు',
    'weather.tomorrow': 'రేపు',
    'weather.weatherWarnings': 'వాతావరణ హెచ్చరికలు',
    'weather.noWarnings': 'సక్రియ వాతావరణ హెచ్చరికలు లేవు',
    
    // Market Trends
    'market.title': 'మార్కెట్ ట్రెండ్స్',
    'market.subtitle': 'నిజ-సమయ పంట ధరలు మరియు మార్కెట్ అంతర్దృష్టులు',
    'market.prices': 'ప్రస్తుత ధరలు',
    'market.trends': 'ధర ట్రెండ్స్',
    'market.forecasting': 'ధర అంచనా',
    'market.crop': 'పంట',
    'market.currentPrice': 'ప్రస్తుత ధర',
    'market.change': 'మార్పు',
    'market.volume': 'పరిమాణం',
    'market.high': 'అధిక',
    'market.low': 'తక్కువ',
    'market.last7Days': 'గత 7 రోజులు',
    'market.last30Days': 'గత 30 రోజులు',
    'market.last3Months': 'గత 3 నెలలు',
    'market.location': 'స్థానం',
    'market.selectLocation': 'స్థానీయ మార్కెట్ డేటా కోసం మీ స్థానాన్ని ఎంచుకోండి',
    'market.andhrapradesh': 'ఆంధ్రప్రదేశ్',
    'market.telangana': 'తెలంగాణ',
    'market.karnataka': 'కర్ణాటక',
    'market.tamilnadu': 'తమిళనాడు',
    'market.forecastingDesc': 'రాబోయే 3 నెలలకు ఊహించిన ధర ట్రెండ్స్',
    'market.increaseExpected': 'పెరుగుదల ఊహించబడుతోంది',
    'market.decreaseExpected': 'తగ్గుదల ఊహించబడుతోంది',
    'market.stablePrices': 'స్థిరమైన ధరలు',
    'market.nextQuarter': 'తదుపరి త్రైమాసికం',
    'market.locationPermission': 'స్థాన అనుమతి అవసరం',
    'market.locationNotice': 'మీ ప్రాంతానికి ప్రత్యేకమైన ఖచ్చితమైన మార్కెట్ డేటాను అందించడానికి, దయచేసి స్థాన ప్రవేశాన్ని అనుమతించండి లేదా మీ స్థానాన్ని మాన్యువల్‌గా ఎంటర్ చేయండి.',
    'market.enterLocation': 'మీ స్థానాన్ని ఎంటర్ చేయండి...',
    'market.useCurrentLocation': 'ప్రస్తుత స్థానాన్ని ఉపయోగించండి',
    
    // Soil Analysis
    'soil.title': 'మట్టి విశ్లేషణ',
    'soil.subtitle': 'సమగ్ర మట్టి ఆరోగ్య మూల్యాంకనం మరియు సిఫారసులు',
    
    // Disease Detection
    'disease.title': 'వ్యాధి గుర్తింపు',
    'disease.subtitle': 'AI-ఆధారిత మొక్కల వ్యాధి గుర్తింపు మరియు చికిత్స సిఫార్సులు',
    'disease.uploadImage': 'మొక్క చిత్రాన్ని అప్‌లోడ్ చేయండి',
    'disease.dragDrop': 'ఇక్కడ ఒక చిత్రాన్ని లాగి వదలండి, లేదా ఎంచుకోవడానికి క్లిక్ చేయండి',
    'disease.analyzing': 'చిత్రాన్ని విశ్లేషిస్తోంది...',
    'disease.results': 'గుర్తింపు ఫలితాలు',
    'disease.confidence': 'విశ్వసనీయత',
    'disease.symptoms': 'లక్షణాలు',
    'disease.treatment': 'చికిత్స',
    'disease.prevention': 'నివారణ',
    'disease.newAnalysis': 'మరొక చిత్రాన్ని విశ్లేషించండి',
    'disease.healthy': 'మొక్క ఆరోగ్యంగా కనిపిస్తోంది',
    'disease.detected': 'వ్యాధి గుర్తించబడింది',
    'disease.uploadAnother': 'మరొక చిత్రాన్ని అప్‌లోడ్ చేయండి',
    
    // Voice Assistant
    'voice.title': 'వాయిస్ అసిస్టెంట్',
    'voice.subtitle': 'వ్యవసాయ ప్రశ్నల గురించి మా AI అసిస్టెంట్‌తో మాట్లాడండి',
    'voice.listening': 'వింటోంది...',
    'voice.processing': 'ప్రాసెసింగ్...',
    'voice.speaking': 'మాట్లాడుతోంది...',
    'voice.startVoiceChat': 'వాయిస్ చాట్ ప్రారంభించండి',
    'voice.stopListening': 'వినడం ఆపండి',
    'voice.conversation': 'సంభాషణ',
    'voice.placeholder': 'ఇక్కడ మీ వ్యవసాయ ప్రశ్నను టైప్ చేయండి...',
    'voice.clearChat': 'చాట్‌ను క్లియర్ చేయండి',
    'voice.audioEnabled': 'ఆడియో ప్రారంభించబడింది',
    'voice.audioDisabled': 'ఆడియో నిలిపివేయబడింది',
    'voice.greeting': 'నమస్కారం! నేను మీ AI వ్యవసాయ అసిస్టెంట్‌ని. మీరు పంటల వ్యాధులు, వాతావరణ నమూనాలు, మట్టి నిర్వహణ, కీటకాల నియంత్రణ లేదా ఏదైనా ఇతర వ్యవసాయ విషయాల గురించి నన్ను అడగవచ్చు. మీరు నాతో మాట్లాడవచ్చు లేదా మీ ప్రశ్నలను టైప్ చేయవచ్చు.',
    
    // Chatbot
    'chat.title': 'AI అసిస్టెంట్',
    'chat.subtitle': 'వ్యవసాయం, పంటలు లేదా వ్యవసాయం గురించి నన్ను ఏదైనా అడగండి',
    'chat.placeholder': 'ఇక్కడ మీ ప్రశ్నను టైప్ చేయండి...',
    'chat.send': 'పంపండి',
    'chat.greeting': 'నమస్కారం! నేను మీ వ్యవసాయ AI అసిస్టెంట్‌ని. ఈరోజు నేను మీకు ఎలా సహాయం చేయగలను?',
    'chat.aiAssistant': 'AI అసిస్టెంట్',
    'chat.farmingAssistant': 'మా AI వ్యవసాయ అసిస్టెంట్‌తో సంభాషణ ప్రారంభించడానికి ఫ్లోటింగ్ చాట్ బటన్‌ను ఉపయోగించండి.',
    'chat.backToHome': 'హోమ్‌కు తిరిగి',
    
    // Footer
    'footer.aboutUs': 'మా గురించి',
    'footer.services': 'సేవలు',
    'footer.support': 'మద్దతు',
    'footer.contact': 'సంప్రదించండి',
    'footer.cropPrediction': 'పంట అంచనా',
    'footer.weatherData': 'వాతావరణ డేటా',
    'footer.soilAnalysis': 'మట్టి విశ్లేషణ',
    'footer.marketInsights': 'మార్కెట్ అంతర్దృష్టులు',
    'footer.helpCenter': 'సహాయ కేంద్రం',
    'footer.documentation': 'డాక్యుమెంటేషన్',
    'footer.faq': 'తరచుగా అడిగే ప్రశ్నలు',
    'footer.customerSupport': 'కస్టమర్ సపోర్ట్',
    'footer.rights': 'అన్ని హక్కులు రక్షించబడ్డాయి',
    'footer.termsOfService': 'సేవా నిబంధనలు',
    'footer.privacyPolicy': 'గోప్యతా విధానం',
    
    // Common
    'common.back': 'వెనుకకు',
    'common.next': 'తదుపరి',
    'common.loading': 'లోడ్ అవుతోంది...',
    'common.error': 'లోపం',
    'common.success': 'విజయం',
    'common.cancel': 'రద్దు చేయండి'
  }
};

interface LanguageProviderProps {
  children: ReactNode;
}

export function LanguageProvider({ children }: LanguageProviderProps) {
  const [language, setLanguage] = useState<Language>('en');

  const t = useMemo(() => {
    return (key: string): string => {
      return translations[language][key as keyof typeof translations[typeof language]] || key;
    };
  }, [language]);

  const contextValue = useMemo(() => ({
    language,
    setLanguage,
    t
  }), [language, t]);

  return (
    <LanguageContext.Provider value={contextValue}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}